### ISSUE TITLE
AttributeError: '_Scholarly' object has no attribute 'use_proxy'

### ISSUE THREAD

**Issue by gambastyle** [scholarly-python-package/scholarly#107]
Can't understand why there is no attribute for use_proxy, im in the latest version. Is this because i'm windows user?

  File "<ipython-input-29-a507d97cf0c6>", line 1, in <module>
    scholarly.use_proxy(http=proxy, https=proxy)

AttributeError: '_Scholarly' object has no attribute 'use_proxy'

**Comment by emilepetrone** [comment]
This fixes it - `use_proxy` is on `nav`.

`scholarly.nav.use_proxy(**proxies)`

**Comment by emilepetrone** [comment]
On this issue, there is a bug where pip installs a different version of scholarly than what is in this repo. If you do not use the scholarly in this repo, you will run into this error, or an AttributeError `module scholarly.scholarly has no attribute nav`. I believe that is what this issue is really getting at.

**Comment by gambastyle** [comment]
Thank you very much for your reply, and indeed the scholarly.nav.use_proxy executed the command, however its seems like its stuck when iterating the search query (which doesn’t happen without proxy), you think you know why its stuck?

 

Thanks a lot for the support, appreciate it,

Itay

**Comment by silvavn** [comment]
To improve the pattern, I have included a `use_proxy` method in Scholarly now.

**Comment by gambastyle** [comment]
This is the error I get:

 

search_query = scholarly.search_author("name")

 

df_search = pd.DataFrame(map(vars, search_query))

Traceback (most recent call last):

 

  File "D:\Dropbox\Anaconda\lib\site-packages\urllib3\connectionpool.py", line 380, in _make_request

    httplib_response = conn.getresponse(buffering=True)

 

TypeError: getresponse() got an unexpected keyword argument 'buffering'

 

 

During handling of the above exception, another exception occurred:

 

Traceback (most recent call last):

 

  File "D:\Dropbox\Anaconda\lib\site-packages\urllib3\contrib\pyopenssl.py", line 280, in recv_into

    return self.connection.recv_into(*args, **kwargs)

 

  File "D:\Dropbox\Anaconda\lib\site-packages\OpenSSL\SSL.py", line 1840, in recv_into

    self._raise_ssl_error(self._ssl, result)

 

  File "D:\Dropbox\Anaconda\lib\site-packages\OpenSSL\SSL.py", line 1646, in _raise_ssl_error

    raise WantReadError()

 

WantReadError

 

 

During handling of the above exception, another exception occurred:

 

Traceback (most recent call last):

 

  File "<ipython-input-21-e2657dc6ba52>", line 1, in <module>

    df_search = pd.DataFrame(map(vars, search_query))

 

  File "C:\Users\itaya\AppData\Roaming\Python\Python37\site-packages\pandas\core\frame.py", line 469, in __init__

    data = list(data)

 

  File "D:\Dropbox\Anaconda\lib\site-packages\scholarly\_navigator.py", line 172, in search_authors

    soup = self._get_soup(url)

 

  File "D:\Dropbox\Anaconda\lib\site-packages\scholarly\_navigator.py", line 161, in _get_soup

    html = self._get_page(_HOST.format(url))

 

  File "D:\Dropbox\Anaconda\lib\site-packages\scholarly\_navigator.py", line 86, in _get_page

    timeout=_TIMEOUT)

 

  File "D:\Dropbox\Anaconda\lib\site-packages\requests\sessions.py", line 521, in get

    return self.request('GET', url, **kwargs)

 

  File "D:\Dropbox\Anaconda\lib\site-packages\requests\sessions.py", line 508, in request

    resp = self.send(prep, **send_kwargs)

 

  File "D:\Dropbox\Anaconda\lib\site-packages\requests\sessions.py", line 640, in send

    history = [resp for resp in gen] if allow_redirects else []

 

  File "D:\Dropbox\Anaconda\lib\site-packages\requests\sessions.py", line 640, in <listcomp>

    history = [resp for resp in gen] if allow_redirects else []

 

  File "D:\Dropbox\Anaconda\lib\site-packages\requests\sessions.py", line 218, in resolve_redirects

    **adapter_kwargs

 

  File "D:\Dropbox\Anaconda\lib\site-packages\requests\sessions.py", line 618, in send

    r = adapter.send(request, **kwargs)

 

  File "D:\Dropbox\Anaconda\lib\site-packages\requests\adapters.py", line 440, in send

    timeout=timeout

 

  File "D:\Dropbox\Anaconda\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen

    chunked=chunked)

 

  File "D:\Dropbox\Anaconda\lib\site-packages\urllib3\connectionpool.py", line 383, in _make_request

    httplib_response = conn.getresponse()

 

  File "D:\Dropbox\Anaconda\lib\http\client.py", line 1336, in getresponse

    response.begin()

 

  File "D:\Dropbox\Anaconda\lib\http\client.py", line 306, in begin

    version, status, reason = self._read_status()

 

  File "D:\Dropbox\Anaconda\lib\http\client.py", line 267, in _read_status

    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")

 

  File "D:\Dropbox\Anaconda\lib\socket.py", line 589, in readinto

    return self._sock.recv_into(b)

 

  File "D:\Dropbox\Anaconda\lib\site-packages\urllib3\contrib\pyopenssl.py", line 292, in recv_into

    rd = util.wait_for_read(self.socket, self.socket.gettimeout())

 

  File "D:\Dropbox\Anaconda\lib\site-packages\urllib3\util\wait.py", line 33, in wait_for_read

    return _wait_for_io_events(socks, EVENT_READ, timeout)

 

  File "D:\Dropbox\Anaconda\lib\site-packages\urllib3\util\wait.py", line 26, in _wait_for_io_events

    selector.select(timeout) if key[1] & events]

 

  File "D:\Dropbox\Anaconda\lib\site-packages\urllib3\util\selectors.py", line 320, in select

    self._writers, timeout)

 

  File "D:\Dropbox\Anaconda\lib\site-packages\urllib3\util\selectors.py", line 64, in _syscall_wrapper

    return func(*args, **kwargs)

 

  File "D:\Dropbox\Anaconda\lib\site-packages\urllib3\util\selectors.py", line 310, in _select

    return select.select(r, w, [], timeout)
