### ISSUE TITLE
search_pubs doesn't work

### ISSUE THREAD

**Issue by FrancoisMoreau** [scholarly-python-package/scholarly#139]
Hi, I was trying to use in your tutorial:
```
>>> search_query = scholarly.search_pubs('Perception of physical stability and center of mass of 3D objects')
>>> print(next(search_query))
```

However, it doesn't work. 
Error mesage:
`Traceback (most recent call last):
  File "test.py", line 5, in <module>
    search_query = scholarly.search_pubs('Perception of physical stability and center of mass of 3D objects')
  File "/Users/brayden/.virtualenvs/score/lib/python3.7/site-packages/scholarly/_scholarly.py", line 134, in search_pubs
    return self.__nav.search_publications(url)
  File "/Users/brayden/.virtualenvs/score/lib/python3.7/site-packages/scholarly/_navigator.py", line 326, in search_publications
    return _SearchScholarIterator(self, url)
  File "/Users/brayden/.virtualenvs/score/lib/python3.7/site-packages/scholarly/publication.py", line 24, in __init__
    self._load_url(url)
  File "/Users/brayden/.virtualenvs/score/lib/python3.7/site-packages/scholarly/publication.py", line 28, in _load_url
    self._soup = self._nav._get_soup(url)
  File "/Users/brayden/.virtualenvs/score/lib/python3.7/site-packages/scholarly/_navigator.py", line 271, in _get_soup
    html = self._get_page(_HOST.format(url))
  File "/Users/brayden/.virtualenvs/score/lib/python3.7/site-packages/scholarly/_navigator.py", line 121, in _get_page
    raise Exception("Cannot fetch the page from Google Scholar.")
Exception: Cannot fetch the page from Google Scholar.`

It tried several versions, I think it's ok before version 0.2.5.
Thanks.

**Comment by AZhyrenkov** [comment]
Experiencing the same with `search_author`:
```Traceback (most recent call last):
  File "test.py", line 7, in <module>
    author = next(search_query).fill()
  File "/Users/aleksey.zhirenkov/Documents/01_projects/freelance/shogle/venv/lib/python3.7/site-packages/scholarly/_navigator.py", line 282, in search_authors
    soup = self._get_soup(url)
  File "/Users/aleksey.zhirenkov/Documents/01_projects/freelance/shogle/venv/lib/python3.7/site-packages/scholarly/_navigator.py", line 271, in _get_soup
    html = self._get_page(_HOST.format(url))
  File "/Users/aleksey.zhirenkov/Documents/01_projects/freelance/shogle/venv/lib/python3.7/site-packages/scholarly/_navigator.py", line 121, in _get_page
    raise Exception("Cannot fetch the page from Google Scholar.")
Exception: Cannot fetch the page from Google Scholar.      
```

**Comment by AZhyrenkov** [comment]
I have packed the script into separated docker container with only python, scholarly and tor inside, and it still shows the same:
```
root@bf5ef5d71c1d:/app# service tor start
[ ok ] Starting tor daemon...done.
root@bf5ef5d71c1d:/app# service tor status
[ ok ] tor is running.
root@bf5ef5d71c1d:/app# python test.py 
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    author = next(search_query).fill()
  File "/usr/local/lib/python3.7/site-packages/scholarly/_navigator.py", line 303, in search_authors
    soup = self._get_soup(url)
  File "/usr/local/lib/python3.7/site-packages/scholarly/_navigator.py", line 292, in _get_soup
    html = self._get_page(_HOST.format(url))
  File "/usr/local/lib/python3.7/site-packages/scholarly/_navigator.py", line 129, in _get_page
    raise Exception("Cannot fetch the page from Google Scholar.")
Exception: Cannot fetch the page from Google Scholar.
```

Where `test.py` is simple:
```
from scholarly import scholarly
search_query = scholarly.search_author('Steven A Cholewiak')
author = next(search_query).fill()
print(author)
```

BTW: if you think it's needed, can add a MR with Dockerfile + docker-compose for usage

**Comment by ipeirotis** [comment]
This seems to be a problem where Google Scholar blocks your computer.

I just tried the following:

```bash
$ pip3 install -U scholarly
$ sudo apt-get install tor
```

And then

```python
import random
from scholarly import scholarly
from pprint import pprint

result = scholarly.launch_tor('/usr/bin/tor',
                     tor_sock_port=random.randint(9000, 9499),
                     tor_control_port=random.randint(9500, 9999))

pprint(result)
```
Returns 
```
{'proxies': {'http': 'socks5://127.0.0.1:9032',
             'https': 'socks5://127.0.0.1:9032'},
 'proxy_works': True,
 'refresh_works': True,
 'tor_control_port': 9554,
 'tor_sock_port': 9032}
```

At this point, I get a confirmation that the Tor installation works, and that the Tor/socks proxy can redirect the network calls though the Tor network.

Now, if I issue the request from scholarly:

```python
search_query = scholarly.search_pubs('Perception of physical stability and center of mass of 3D objects')
print(next(search_query))
```

I get 

```
{'bib': {'abstract': 'Humans can judge from vision alone whether an object is '
                     'physically stable or not. Such judgments allow observers '
                     'to predict the physical behavior of objects, and hence '
                     'to guide their motor actions. We investigated the visual '
                     'estimation of physical stability of 3-D objects (shown '
                     'in stereoscopically viewed rendered scenes) and how it '
                     'relates to visual estimates of their center of mass '
                     '(COM). In Experiment 1, observers viewed an object near '
                     'the edge of a table and adjusted its tilt to the '
                     'perceived critical angle, ie, the tilt angle at which '
                     'the object',
         'author': ['SA Cholewiak', 'RW Fleming', 'M Singh'],
         'cites': '19',
         'eprint': 'https://jov.arvojournals.org/article.aspx?articleID=2213254',
         'gsrank': '1',
         'title': 'Perception of physical stability and center of mass of 3-D '
                  'objects',
         'url': 'https://jov.arvojournals.org/article.aspx?articleID=2213254',
         'venue': 'Journal of vision',
         'year': '2015'},
 'citations_link': '/scholar?cites=15736880631888070187&as_sdt=5,33&sciodt=0,33&hl=en',
 'filled': False,
 'source': 'scholar',
 'url_add_sclib': '/citations?hl=en&xsrf=&continue=/scholar%3Fq%3DPerception%2Bof%2Bphysical%2Bstability%2Band%2Bcenter%2Bof%2Bmass%2Bof%2B3D%2Bobjects%26hl%3Den%26as_sdt%3D0,33&citilm=1&json=&update_op=library_add&info=K8ZpoI6hZNoJ&ei=d1nWXtiDN8-_mAGFxbWIDw',
 'url_scholarbib': 'https://scholar.googleusercontent.com/scholar.bib?q=info:K8ZpoI6hZNoJ:scholar.google.com/&output=citation&scisdr=CgXa-v6oGAA:AAGBfm0AAAAAXtZb0zqz2X-uxEz9Oo4jtU072mIaz3JN&scisig=AAGBfm0AAAAAXtZb0xhwARCCyF-3Goy5ZTlKcIHIDxrD&scisf=4&ct=citation&cd=-1&hl=en'}
```

**Comment by ipeirotis** [comment]
If you do not want to use Tor, take a look at the example listed at https://github.com/scholarly-python-package/scholarly/issues/120

**Comment by AZhyrenkov** [comment]
Thank you so much for this reference. Manage to achieve the results successfully :)
Is it killing the tor instance on the execution end?

**Comment by ipeirotis** [comment]
The `launch_tor` _should_ kill the Tor instance when the program exits. If not, please create an issue, as we will need to fix it.
