### ISSUE TITLE
Retrieve multiple papers information by searching keywords 

### ISSUE THREAD

**Issue by JiayuanDing100** [scholarly-python-package/scholarly#145]
Hi,
How to retrieve multiple papers information by searching keywords like "Sentiment Analysis Survey"?

**Comment by silvavn** [comment]
This can be done by:
```python
papers = [a for a in scholarly.search_pubs('Sentiment Analysis Survey')]
```

If you wish to print the information:
```python
for i in papers:
    print(i)
```

**Comment by JiayuanDing100** [comment]
Thanks for reply!
I tried this:
from scholarly import scholarly
papers = [a for a in scholarly.search_pubs('Sentiment Analysis Survey')]
for i in papers:
   print(i)

but the exception was raised!
Traceback (most recent call last):
  File "/Users/djiayuan/Main_Work/UGA/reading_list_paper/reading_list_recommendation/survey/scrawl_survey_title_from_scholar.py", line 3, in <module>
    a = scholarly.search_pubs('Sentiment Analysis Survey')
  File "/Users/djiayuan/.conda/envs/Covid19-Classification/lib/python3.7/site-packages/scholarly/_scholarly.py", line 152, in search_pubs
    return self.__nav.search_publications(url)
  File "/Users/djiayuan/.conda/envs/Covid19-Classification/lib/python3.7/site-packages/scholarly/_navigator.py", line 348, in search_publications
    return _SearchScholarIterator(self, url)
  File "/Users/djiayuan/.conda/envs/Covid19-Classification/lib/python3.7/site-packages/scholarly/publication.py", line 24, in __init__
    self._load_url(url)
  File "/Users/djiayuan/.conda/envs/Covid19-Classification/lib/python3.7/site-packages/scholarly/publication.py", line 28, in _load_url
    self._soup = self._nav._get_soup(url)
  File "/Users/djiayuan/.conda/envs/Covid19-Classification/lib/python3.7/site-packages/scholarly/_navigator.py", line 293, in _get_soup
    html = self._get_page(_HOST.format(url))
  File "/Users/djiayuan/.conda/envs/Covid19-Classification/lib/python3.7/site-packages/scholarly/_navigator.py", line 130, in _get_page
    raise Exception("Cannot fetch the page from Google Scholar.")
Exception: Cannot fetch the page from Google Scholar.

I tracked back the source code and found there is no return in function _get_page in _navigator.py file?

**Comment by silvavn** [comment]
It might be because your computer cannot connect to the internet, too many requests were made.
Consider using a proxy.

**Comment by JiayuanDing100** [comment]
Probably, my IP is banned  by scholar. I tried the proxy via your sample:

from fp.fp import FreeProxy
from scholarly import scholarly
proxy = FreeProxy(rand=True, timeout=1, country_id=['US', 'CA']).get()
scholarly.use_proxy(http=proxy, https=proxy)
papers = [a for a in scholarly.search_pubs('Sentiment Analysis Survey')]
for i in papers:
   print(i)

I got "HTTPSConnectionPool(host='www.sslproxies.org', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError("bad handshake: SysCallError(54, 'ECONNRESET')")))
"

**Comment by AngeloMendes** [comment]
Using proxy, works for me
```
from fp.fp import FreeProxy
from scholarly import scholarly

from scholarly import ProxyGenerator
pg = ProxyGenerator()


proxy = FreeProxy(rand=True, timeout=1, country_id=['BR']).get()

pg.SingleProxy(http =proxy, https =proxy)

scholarly.use_proxy(pg)

author_name="Angelo Cesar Mendes da Silva"
author = next(scholarly.search_author(author_name)).fill()
pubs = author.publications
print(pubs[0])

"""
_output_:
{'bib': {'cites': '2',
         'title': 'A Music Classification model based on metric learning '
                  'applied to MP3 audio files',
         'year': '2020'},
 'filled': False,
 'id_citations': 'uKaUK48AAAAJ:mvPsJ3kp5DgC',
 'source': 'citations'}
"""
```

**Comment by luciantunez** [comment]
you rock!!!!
