### ISSUE TITLE
next(search_query).fill() not working

### ISSUE THREAD

**Issue by CiaoAnkit** [scholarly-python-package/scholarly#300]
Recently, `scholarly` started throwing following error:

```
Traceback (most recent call last):
  File "./citation_report_google.py", line 19, in <module>
    author = next(search_query).fill()
  File "/home/lab1/.local/lib/python3.6/site-packages/scholarly-0.2.4-py3.6.egg/scholarly/scholarly.py", line 270, in fill
  File "/home/lab1/.local/lib/python3.6/site-packages/scholarly-0.2.4-py3.6.egg/scholarly/scholarly.py", line 127, in __init__
  File "/home/lab1/.local/lib/python3.6/site-packages/beautifulsoup4-4.8.0-py3.6.egg/bs4/element.py", line 971, in __getitem__
    return self.attrs[key]
KeyError: 'data-href'
```

**Comment by nxkryptor** [comment]
I too have been getting similar errors from the past two days. The MWE is given below

**Error**
```
Traceback (most recent call last):
  File "scholarly_test.py", line 3, in <module>
    author = scholarly.fill(next(search_query))
  File "/home/georgeeappach/.local/lib/python3.8/site-packages/scholarly/_scholarly.py", line 206, in fill
    object = author_parser.fill(object, sections, sortby, publication_limit)
  File "/home/georgeeappach/.local/lib/python3.8/site-packages/scholarly/author_parser.py", line 332, in fill
    raise(e)
  File "/home/georgeeappach/.local/lib/python3.8/site-packages/scholarly/author_parser.py", line 324, in fill
    (getattr(self, f'_fill_{i}')(soup, author) if i != 'publications' else getattr(self, f'_fill_{i}')(soup, author, publication_limit, sortby_str))
  File "/home/georgeeappach/.local/lib/python3.8/site-packages/scholarly/author_parser.py", line 124, in _fill_publications
    new_pub = pub_parser.get_publication(row, PublicationSource.AUTHOR_PUBLICATION_ENTRY)
  File "/home/georgeeappach/.local/lib/python3.8/site-packages/scholarly/publication_parser.py", line 136, in get_publication
    return self._citation_pub(__data, publication)
  File "/home/georgeeappach/.local/lib/python3.8/site-packages/scholarly/publication_parser.py", line 110, in _citation_pub
    publication['author_pub_id'] = re.findall(_CITATIONPUBRE, __data.find(
  File "/usr/lib/python3/dist-packages/bs4/element.py", line 1321, in __getitem__
    return self.attrs[key]
KeyError: 'data-href'
```

**MWE**

```
from scholarly import scholarly
search_query = scholarly.search_author('Steven A Cholewiak')
author = scholarly.fill(next(search_query))
```

**Comment by arunkannawadi** [comment]
Does this solution in #297 work? - https://github.com/scholarly-python-package/scholarly/issues/297#issuecomment-877185922

**Comment by CiaoAnkit** [comment]
I was on an older version of scholarly. In my `scholarly.py`, I replaced
`self.id_citations = re.findall(_CITATIONPUBRE, __data.find('a', class_='gsc_a_at')['data-href'])[0]`
with 
`self.id_citations = re.findall(_CITATIONPUBRE, str(__data))[0]`

PS: Thanks @joan-navarro for the hint in #297 and @arunkannawadi for pointing towards it.
