### ISSUE TITLE
search_pubs returning MaxTriesExceededException

### ISSUE THREAD

**Issue by ojsellers** [scholarly-python-package/scholarly#302]
Hi guys,

I'm getting the below when using the search_pubs example from the docs with a fresh test environment. My first thought was being blocked but I can still use the search_author and .fill fine after using joan-navarro's solution from issue #297.

>>> from scholarly import scholarly
>>> search_query = scholarly.search_pubs('Perception of physical stability and center of mass of 3D objects')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/olliesellers/miniconda3/envs/test_env/lib/python3.8/site-packages/scholarly/_scholarly.py", line 149, in search_pubs
    return self.__nav.search_publications(url)
  File "/Users/olliesellers/miniconda3/envs/test_env/lib/python3.8/site-packages/scholarly/_navigator.py", line 269, in search_publications
    return _SearchScholarIterator(self, url)
  File "/Users/olliesellers/miniconda3/envs/test_env/lib/python3.8/site-packages/scholarly/publication_parser.py", line 53, in __init__
    self._load_url(url)
  File "/Users/olliesellers/miniconda3/envs/test_env/lib/python3.8/site-packages/scholarly/publication_parser.py", line 59, in _load_url
    self._soup = self._nav._get_soup(url)
  File "/Users/olliesellers/miniconda3/envs/test_env/lib/python3.8/site-packages/scholarly/_navigator.py", line 212, in _get_soup
    html = self._get_page('https://scholar.google.com{0}'.format(url))
  File "/Users/olliesellers/miniconda3/envs/test_env/lib/python3.8/site-packages/scholarly/_navigator.py", line 164, in _get_page
    raise MaxTriesExceededException("Cannot Fetch from Google Scholar.")
scholarly._navigator.MaxTriesExceededException: Cannot Fetch from Google Scholar.

Would be grateful for any help anyone can offer.

Thanks

**Comment by ipeirotis** [comment]
Seach_pubs is officially blocked in robots.txt by Google, while search_author is not.
