### ISSUE TITLE
Bibtext Export  issue

### ISSUE THREAD

**Issue by Biotopp** [scholarly-python-package/scholarly#441]
The feature of exporting a publication to Bibtex doesn't work ..
Thank you so much for effort!
I really appreciate that !
![Screenshot](https://user-images.githubusercontent.com/105524985/194297608-bfd0aa17-e3c5-48de-b837-e5bb5eff6138.jpg)

**Comment by arunkannawadi** [comment]
Thanks for the report. Could you post the full error message in text format here? There are some other open issues related to bibtex, so this might be a duplicate.

**Comment by Biotopp** [comment]
It's my pleasure! here it is:

> Traceback (most recent call last):
  File "C:/Users/Science/Downloads/Test scholarly/main.py", line 2, in <module>
    query = scholarly.search_pubs("A density-based algorithm for discovering clusters in large spatial databases with noise")
  File "C:\Users\Science\AppData\Local\Programs\Python\Python37\lib\site-packages\scholarly\_scholarly.py", line 156, in search_pubs
    return self.__nav.search_publications(url)
  File "C:\Users\Science\AppData\Local\Programs\Python\Python37\lib\site-packages\scholarly\_navigator.py", line 283, in search_publications
    return _SearchScholarIterator(self, url)
  File "C:\Users\Science\AppData\Local\Programs\Python\Python37\lib\site-packages\scholarly\publication_parser.py", line 53, in __init__
    self._load_url(url)
  File "C:\Users\Science\AppData\Local\Programs\Python\Python37\lib\site-packages\scholarly\publication_parser.py", line 59, in _load_url
    self._soup = self._nav._get_soup(url)
  File "C:\Users\Science\AppData\Local\Programs\Python\Python37\lib\site-packages\scholarly\_navigator.py", line 226, in _get_soup
    html = self._get_page('https://scholar.google.com{0}'.format(url))
  File "C:\Users\Science\AppData\Local\Programs\Python\Python37\lib\site-packages\scholarly\_navigator.py", line 177, in _get_page
    raise MaxTriesExceededException("Cannot Fetch from Google Scholar.")
scholarly._proxy_generator.MaxTriesExceededException: Cannot Fetch from Google Scholar.

Process finished with exit code 1

**Comment by arunkannawadi** [comment]
The error seems to be coming from `search_pubs` method and not from `bibtex` method. You'll need to setup a proxy to do this successfully, since Google Scholar blocks any automated request to search for publications in its database. There's a section in our documentation on how to set it up: https://scholarly.readthedocs.io/en/stable/quickstart.html#using-proxies
