### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'follow_redirects'

### ISSUE THREAD

**Issue by sanbeichahegongheguo** [scholarly-python-package/scholarly#502]
**Describe the bug**
from scholarly import scholarly

Traceback (most recent call last):
  File "13test.py", line 4, in <module>
    from scholarly import scholarly
  File "C:\JupyterLab\resources\jlab_server\lib\site-packages\scholarly\__init__.py", line 4, in <module>
    scholarly = _Scholarly()
  File "C:\JupyterLab\resources\jlab_server\lib\site-packages\scholarly\_scholarly.py", line 34, in __init__
    self.__nav = Navigator()
  File "C:\JupyterLab\resources\jlab_server\lib\site-packages\scholarly\_navigator.py", line 27, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args,
  File "C:\JupyterLab\resources\jlab_server\lib\site-packages\scholarly\_navigator.py", line 43, in __init__
    self.pm1 = ProxyGenerator()
  File "C:\JupyterLab\resources\jlab_server\lib\site-packages\scholarly\_proxy_generator.py", line 62, in __init__
    self._new_session()
  File "C:\JupyterLab\resources\jlab_server\lib\site-packages\scholarly\_proxy_generator.py", line 486, in _new_session
    self._session = httpx.Client(**init_kwargs)
TypeError: __init__() got an unexpected keyword argument 'follow_redirects'

**To Reproduce**
from scholarly import scholarly

when  I run the code, then report the bug.

**Desktop (please complete the following information):**
 - python version: 3.8.12
 - OS: win11
 - Version 1.7.11

**Comment by sanbeichahegongheguo** [comment]
find 
scholarly\_proxy_generator.py", in  line 454
and rewrite code
```
        # init_kwargs = {"follow_redirects": True}
        init_kwargs = {}
```
